### PR TITLE
added gears and belts shader

### PR DESCRIPTION
**Pull request by rakshith-git**

### CODE REVIEW

**Comment by m-ahdal** [comment]
Do you have a preview for this btw?

**Comment by rakshith-git** [comment]
Will the video i posted on discord work?

**Comment by rakshith-git** [comment]
> Do you have a preview for this btw?

**Comment by m-ahdal** [comment]
Tag me! I'll check it out. I'll merge it in the meanwhile - I'm just curious :)

**Comment by rakshith-git** [comment]
> Tag me! I'll check it out. I'll merge it in the meanwhile - I'm just curious :) 

https://discord.com/channels/1005603569187160125/1265734485757136956/1322668115141722163

Someone else recommend me to push it here I thought it was you lol 😄 hope you like it

**Comment by alex-sherwin** [comment]
For future people looking for a preview

gears-and-belts


https://github.com/user-attachments/assets/b03196f6-cfc9-4696-857d-7629751bdf75

**Pull request merged**
